# Project-wide Gradle settings.
# For more details on how to configure your build, visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Enable AndroidX and automatic conversion of third-party libraries
android.useAndroidX=true
android.enableJetifier=true

# Kotlin style
kotlin.code.style=official

# JVM configuration
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
